name: Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'arlo-co.com/**'
      - 'yoursturdyhome.com/**'

jobs:
  build-arlo-co:
    if: contains(github.event.head_commit.message, 'arlo-co.com')
    runs-on: ubuntu-latest
    name: Deploy arlo-co.com

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy arlo-co.com to S3 bucket (www)
        run: aws s3 sync ./arlo-co.com s3://www.arlo-co.com --delete

      - name: Deploy arlo-co.com to S3 bucket (root)
        run: aws s3 sync ./arlo-co.com s3://arlo-co.com --delete

      - name: Clear CloudFront cache for arlo-co.com
        run: aws cloudfront create-invalidation --distribution-id E35G6ANT6H3J1 --paths "/*"

  build-yoursturdyhome:
    if: contains(github.event.head_commit.message, 'yoursturdyhome.com')
    runs-on: ubuntu-latest
    name: Deploy yoursturdyhome.com

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy yoursturdyhome.com to S3 bucket (www)
        run: aws s3 sync ./yoursturdyhome.com s3://www.yoursturdyhome.com --delete

      - name: Deploy yoursturdyhome.com to S3 bucket (root)
        run: aws s3 sync ./yoursturdyhome.com s3://yoursturdyhome.com --delete

      - name: Clear CloudFront cache for yoursturdyhome.com
        run: aws cloudfront create-invalidation --distribution-id E3BBMVKN7MAT8C --paths "/*"
